openapi: 3.0.0
info:
  title: Grayscale Image API - STD22064
  version: 1.0.0
paths:
  /black-and-white/{id}:
    put:
      summary: Upload and process a black and white image
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
        - in: header
          name: Content-Type
          required: true
          schema:
            type: string
          enum:
            - image/png
      requestBody:
        required: true
        content:
          image/png:
            schema:
              type: string
              format: binary
      responses:
        '200':
          description: Successful processing
          content:
            application/json:
              schema:
                type: object
        'default':
          description: Unexpected error
    get:
      summary: Retrieve information about a previous operation
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful retrieval
          content:
            application/json:
              schema:
                type: object
                properties:
                  original_url:
                    type: string
                    format: uri
                  transformed_url:
                    type: string
                    format: uri
        'default':
          description: Unexpected error
